# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
# This will include the necessary source files folders in the PATH to be able to generate the documentation from.
# folder = '../venv/lib/python3.8/site-packages/ad_api/api/sp/'
# folder = '../venv/lib/python3.8/site-packages/ad_api/'
folder = '../ad_api/api/'

print(folder)
print(os.path.abspath('.'))
print(os.path.abspath(folder))

# sys.path.insert(0, folder)

# sys.path.insert(0, os.path.abspath('.'))

sys.path.insert(0, os.path.abspath(folder))

print(sys.path)

# sys.exit()

# sys.path.insert(0, '/Users/hanuman/Documents/PycharmProjects/python-amazon-ad-api-1-0-3/venv/lib/python3.8/site-packages/ad_api/api/')

if os.path.isdir(folder):
    print('have')
else:
    print('do not have')

# -- Project information -----------------------------------------------------

project = 'Python Amazon Advertising Api v0.0.2'
copyright = '2021, daniel'
author = 'daniel'

# The full version, including alpha/beta/rc tags
release = '2021'


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
#
# extensions = ['sphinx.ext.autodoc']
# extensions = ['myst_parser', 'sphinx.ext.autodoc']

extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.napoleon',
    'sphinx.ext.viewcode',
    'myst_parser'
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
# language = 'python'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
# html_theme = 'alabaster'
html_theme = 'classic'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']